baseURL = 'https://tecknicaltom.github.io'
languageCode = 'en-us'
title = 'modTwo'
theme = 'ananke'

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/tecknicaltom"

[[params.ananke_socials]]
name = "mastodon"
url = "https://mastodon.neg9.org/@tecknicaltom"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/tecknicaltom"
